name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements
      run: pip install -r config/requirements.txt
    - name: Update Submodules
      run: git submodule init; git submodule update
    - name: Run tests and collect coverage
      run: pytest --cov=address_planner --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3